# Generated by Django 6.0.6 on 2026-06-12 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('length_mode', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('detailed', 'Detailed')], default='medium', max_length=10)),
                ('tone', models.CharField(choices=[('confident', 'Confident'), ('humble', 'Humble'), ('balanced', 'Balanced')], default='balanced', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
